apiVersion: v1
kind: Service
metadata:
  name: {{ include "argo-nginx.fullname" . }}
  labels:
    {{- include "argo-nginx.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{ toYaml .Values.service.loadBalancerSourceRanges | indent 4 }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "argo-nginx.selectorLabels" . | nindent 4 }}
