apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-a
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: nginx-a
    server: 'https://kubernetes.default.svc'
  source:
    path: app-nginx
    repoURL: 'https://github.com/dmilan77/gitops-demo.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
